# Generated by Django 5.2.8 on 2025-11-19 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.FileField(max_length=500, upload_to='models/', verbose_name='Файл')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
            ],
            options={
                'verbose_name': 'Модель ИИ',
                'verbose_name_plural': 'Модели ИИ',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
            ],
            options={
                'verbose_name': 'Набор фото',
                'verbose_name_plural': 'Наборы фото',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LepImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_key', models.CharField(help_text='Путь в бакете MinIO (например: uploads/2025/11/18/dronex/12345.tiff)', max_length=500, verbose_name='Оригинал')),
                ('preview', models.CharField(blank=True, help_text='Путь в бакете на превью MinIO (например: uploads/2025/11/18/dronex/12345.tiff)', max_length=500, null=True, verbose_name='Превью')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Широта (GPS) снимка', max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Долгота (GPS) снимка', max_digits=9, null=True, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Создано')),
                ('detection_result', models.JSONField(blank=True, null=True, verbose_name='Результат')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vision.batch', verbose_name='Контейнер')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ['-created_at'],
            },
        ),
    ]
