# Generated by Django 5.2.8 on 2025-11-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
    ]
